### ISSUE TITLE
香奈枝线，突然出现的竖字框

### ISSUE THREAD

**Issue by lexemaki** [HIllya51/MuramasaHorizontal#1]
![Snipaste_2024-02-28_21-58-56](https://github.com/HIllya51/MuramasaHorizontal/assets/109960039/0be6b291-1d1d-426d-bc43-3681bcfa17ef)

**Comment by HIllya51** [comment]
只有这一句还是这一段都是这样？

**Comment by HIllya51** [comment]
https://github.com/HIllya51/MuramasaHorizontal/blob/main/nss.origin/mc01_005.nss
这段脚本就是在这里，控制方向的我看了就只有SetTextEXC和TypeBeginCIFO，按理说应该没问题，有问题我也不知道咋办咯，稍微忍忍吧😂

**Comment by lexemaki** [comment]
> 只有这一句还是这一段都是这样？

一整段都是这样，我重新开了个档解决了

**Comment by HIllya51** [comment]
什么意思，没看明白，是重新存档然后读档就好了嘛？

**Comment by lexemaki** [comment]
> 什么意思，没看明白，是重新存档然后读档就好了嘛？
是从头开始开了一个新的存档

**Comment by HIllya51** [comment]
还是没懂。不过解决了就行
